// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4TavVwIiDNukTk25hK4_ZKO8E0AyS26M',
    appId: '1:655455782082:web:7daa45a5baaaafad9ae75b',
    messagingSenderId: '655455782082',
    projectId: 'flutter-firebase-6ce5a',
    authDomain: 'flutter-firebase-6ce5a.firebaseapp.com',
    storageBucket: 'flutter-firebase-6ce5a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAf2Yxj-StQw_xsnm2P484NB9TUuOOg4LE',
    appId: '1:655455782082:android:f2761194ab6654a79ae75b',
    messagingSenderId: '655455782082',
    projectId: 'flutter-firebase-6ce5a',
    storageBucket: 'flutter-firebase-6ce5a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZJBM-GKCMQ8TjzGUfsj8wSy7o8yPORmI',
    appId: '1:655455782082:ios:f6fed47c0000d0da9ae75b',
    messagingSenderId: '655455782082',
    projectId: 'flutter-firebase-6ce5a',
    storageBucket: 'flutter-firebase-6ce5a.appspot.com',
    iosBundleId: 'com.example.yazlab22',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZJBM-GKCMQ8TjzGUfsj8wSy7o8yPORmI',
    appId: '1:655455782082:ios:3f1f64c6f6e388539ae75b',
    messagingSenderId: '655455782082',
    projectId: 'flutter-firebase-6ce5a',
    storageBucket: 'flutter-firebase-6ce5a.appspot.com',
    iosBundleId: 'com.example.yazlab22.RunnerTests',
  );
}
